INSERT INTO PERSON(`ID`, `NAME`, `AGE`, `BLOOD_TYPE`, `YEAR_OF_BIRTHDAY`, `MONTH_OF_BIRTHDAY`, `DAY_OF_BIRTHDAY`) VALUES (1, 'martin', 10, 'A', 1991, 8, 15);
INSERT INTO PERSON(`ID`, `NAME`, `AGE`, `BLOOD_TYPE`, `YEAR_OF_BIRTHDAY`, `MONTH_OF_BIRTHDAY`, `DAY_OF_BIRTHDAY`) VALUES (2, 'david', 9, 'B', 1992, 7, 21);
INSERT INTO PERSON(`ID`, `NAME`, `AGE`, `BLOOD_TYPE`, `YEAR_OF_BIRTHDAY`, `MONTH_OF_BIRTHDAY`, `DAY_OF_BIRTHDAY`) VALUES (3, 'dennis', 8, 'O', 1993, 10, 15);
INSERT INTO PERSON(`ID`, `NAME`, `AGE`, `BLOOD_TYPE`, `YEAR_OF_BIRTHDAY`, `MONTH_OF_BIRTHDAY`, `DAY_OF_BIRTHDAY`) VALUES (4, 'sophia', 7, 'AB', 1994, 8, 31);
INSERT INTO PERSON(`ID`, `NAME`, `AGE`, `BLOOD_TYPE`, `YEAR_OF_BIRTHDAY`, `MONTH_OF_BIRTHDAY`, `DAY_OF_BIRTHDAY`) VALUES (5, 'benny', 6, 'A', 1995, 12, 23);

INSERT INTO BLOCK(`ID`, `NAME`) VALUES (1, 'dennis');
INSERT INTO BLOCK(`ID`, `NAME`) VALUES (2, 'sophia');

UPDATE PERSON SET BLOCK_ID = 1 WHERE ID = 3;
UPDATE PERSON SET BLOCK_ID = 2 WHERE ID = 4;